In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import nltk
import re
import string
from sklearn.feature_extraction.text import CountVectorizer
from  nltk.corpus import stopwords 

In [2]:
df=pd.read_csv(r'C:\\Users\\Akshay N R\\Desktop\\Data Science\\projects\\project2\\files\\code\\cleanedshuffledresumes.csv',encoding = 'unicode_escape')
df

Category                                    cleaned_resumes
0          0  tanna sujatha object seek challeng role area w...
1          1  maryala vinay reddi profession summari year su...
2          2  buddha vamsi career object year experi databas...
3          1  ranga gaganam profession summari profession su...
4          3  harikrishna akula summari year experi around y...
..       ...                                                ...
74         4  susovan bag seek challeng posit field scienc t...
75         3  hari krishna summari result orient profession ...
76         3  vinay kumar v workday function consult experti...
77         3  venkata saikrishna workday consult profssion s...
78         1  kotani durga prasad object aspir posit organ c...

[79 rows x 2 columns]

In [3]:
import copy

In [4]:
df1=copy.deepcopy(df)

In [5]:
df1.head()

Category                                    cleaned_resumes
0         0  tanna sujatha object seek challeng role area w...
1         1  maryala vinay reddi profession summari year su...
2         2  buddha vamsi career object year experi databas...
3         1  ranga gaganam profession summari profession su...
4         3  harikrishna akula summari year experi around y...

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Category         79 non-null     int64 
 1   cleaned_resumes  79 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.4+ KB


In [7]:
df1.Category.unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [8]:
df1.isnull().sum()

Category           0
cleaned_resumes    0
dtype: int64

In [9]:
df1[(df1.duplicated())]

Category                                    cleaned_resumes
20         1  mareedu lokesh babu profession overview around...
52         1  uidevelop react js develop name krishna profes...

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack

In [11]:
requiredText = df1['cleaned_resumes'].values
requiredTarget = df1['Category'].values

word_vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    stop_words='english')
word_vectorizer.fit(requiredText)
WordFeatures = word_vectorizer.transform(requiredText)

print ("Feature completed .....")

Feature completed .....


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(WordFeatures, requiredTarget, random_state=42, test_size=0.25, stratify=requiredTarget)
x_train.shape, x_test.shape

((59, 3761), (20, 3761))

In [64]:
################ without TFIDF matrices########## 
#preparing a naive bayes model on training data set

from sklearn.naive_bayes import MultinomialNB as MB
from sklearn.naive_bayes import GaussianNB as GB
from sklearn.metrics import f1_score,precision_score,confusion_matrix,recall_score

# Applying Classification model using SVM

In [15]:
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [16]:
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[100,50,0.6,0.05,0.4,0.04,0.1,0.01,0.001,0.0001],
               'C':[14,13,12,11,10,0.1,0.001,0.0001]}]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [14, 13, 12, 11, 10, 0.1, 0.001, 0.0001],
                          'gamma': [100, 50, 0.6, 0.05, 0.4, 0.04, 0.1, 0.01,
                                    0.001, 0.0001],
                          'kernel': ['rbf']}])

In [17]:
gsv.best_params_ , gsv.best_score_ 

({'C': 14, 'gamma': 0.6, 'kernel': 'rbf'}, 0.95)

In [83]:
clf = SVC(kernel='rbf',C=14,gamma=0.015)
clf.fit(x_train , y_train)
y_pred_train= clf.predict(x_train)
acc = accuracy_score(y_train, y_pred_train) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train,y_pred_train))

Accuracy = 94.91525423728814
[[15  0  0  0  0]
 [ 0 16  0  0  0]
 [ 0  1  9  0  0]
 [ 0  0  0 16  0]
 [ 0  2  0  0  0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.84      1.00      0.91        16
           2       1.00      0.90      0.95        10
           3       1.00      1.00      1.00        16
           4       0.00      0.00      0.00         2

    accuracy                           0.95        59
   macro avg       0.77      0.78      0.77        59
weighted avg       0.92      0.95      0.93        59



In [88]:
y_pred_test = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred_test) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test,y_pred_test))

Accuracy = 90.0
[[4 1 0 0]
 [0 6 0 0]
 [0 1 3 0]
 [0 0 0 5]]
              precision    recall  f1-score   support

           0       1.00      0.80      0.89         5
           1       0.75      1.00      0.86         6
           2       1.00      0.75      0.86         4
           3       1.00      1.00      1.00         5

    accuracy                           0.90        20
   macro avg       0.94      0.89      0.90        20
weighted avg       0.93      0.90      0.90        20



In [85]:
accuracy_1 = round(accuracy_score(y_test,y_pred_test),4)
precision_1 = round(precision_score(y_test,y_pred_test,average = 'macro'),4)
recall_1 = round(recall_score(y_test,y_pred_test, average = 'macro'),4)
f1_1 = round(f1_score(y_test,y_pred_test, average = 'macro'),4)
print('Accuracy Score   : ', accuracy_1)
print('Precision Score  : ', precision_1)
print('Recall Score     : ', recall_1)
print('f1-Score         : ', f1_1)
print('Confusion Matrix :\n',confusion_matrix(y_test,y_pred_test))

Accuracy Score   :  0.9
Precision Score  :  0.9375
Recall Score     :  0.8875
f1-Score         :  0.9008
Confusion Matrix :
 [[4 1 0 0]
 [0 6 0 0]
 [0 1 3 0]
 [0 0 0 5]]


# KNN model

In [20]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [21]:
num_folds = 10
kfold = KFold(n_splits=10)

In [22]:
knnmodel = KNeighborsClassifier(n_neighbors=5)
knnmodel.fit(x_train , y_train)
y_pred_trainknn= clf.predict(x_train)
acc = accuracy_score(y_train, y_pred_trainknn) * 100
print("Accuracy =", acc)
#print(confusion_matrix(y_train, y_pred_trainknn))
print(classification_report(y_train,y_pred_trainknn))


Accuracy = 91.52542372881356
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        15
           1       0.80      1.00      0.89        16
           2       1.00      0.70      0.82        10
           3       1.00      1.00      1.00        16
           4       0.00      0.00      0.00         2

    accuracy                           0.92        59
   macro avg       0.75      0.74      0.74        59
weighted avg       0.90      0.92      0.90        59



In [23]:
y_pred_testknn = knnmodel.predict(x_test)
acc = accuracy_score(y_test, y_pred_testknn) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_test, y_pred_testknn))
print(classification_report(y_test,y_pred_testknn))

Accuracy = 100.0
[[5 0 0 0]
 [0 6 0 0]
 [0 0 4 0]
 [0 0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [78]:
accuracy_2 = round(accuracy_score(y_test,y_pred_testknn),4)
precision_2 = round(precision_score(y_test,y_pred_testknn,average = 'macro'),4)
recall_2 = round(recall_score(y_test,y_pred_testknn, average = 'macro'),4)
f1_2 = round(f1_score(y_test,y_pred_testknn, average = 'macro'),4)
print('Accuracy Score   : ', accuracy_2)
print('Precision Score  : ', precision_2)
print('Recall Score     : ', recall_2)
print('f1-Score         : ', f1_2)
print('Confusion Matrix :\n',confusion_matrix(y_test,y_pred_testknn))

Accuracy Score   :  1.0
Precision Score  :  1.0
Recall Score     :  1.0
f1-Score         :  1.0
Confusion Matrix :
 [[5 0 0 0]
 [0 6 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [24]:
knn1model = KNeighborsClassifier(n_neighbors=5)
results = cross_val_score(knn1model, x_train, y_train, cv=kfold)
print(results.mean())

0.9333333333333333


In [25]:
knn2model = KNeighborsClassifier(n_neighbors=5)
results = cross_val_score(knn2model, x_test, y_test, cv=kfold)
print(results.mean())

0.9


In [26]:
knn3model = KNeighborsClassifier(n_neighbors=5)
results = cross_val_score(knn3model, WordFeatures, requiredTarget, cv=kfold)
print(results.mean())

0.9107142857142858


# Building Decision Tree classifier using gini criteria

In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

In [28]:
model_gini = DecisionTreeClassifier(criterion='gini', max_depth=4,max_features='sqrt')

In [29]:
model_gini.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=4, max_features='sqrt')

In [30]:
y_pred_train_gini= model_gini.predict(x_train)
acc = accuracy_score(y_train, y_pred_train_gini) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_train, y_pred_train_gini))
print(classification_report(y_train,y_pred_train_gini))

Accuracy = 93.22033898305084
[[14  0  1  0  0]
 [ 0 16  0  0  0]
 [ 1  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  2  0  0  0]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        15
           1       0.89      1.00      0.94        16
           2       0.90      0.90      0.90        10
           3       1.00      1.00      1.00        16
           4       0.00      0.00      0.00         2

    accuracy                           0.93        59
   macro avg       0.74      0.77      0.75        59
weighted avg       0.90      0.93      0.92        59



In [31]:
y_pred_test_gini=model_gini.predict(x_test)
acc=accuracy_score(y_test, y_pred_test_gini)*100
print("Accuracy=", acc)
print(confusion_matrix(y_test, y_pred_test_gini))
print(classification_report(y_test,y_pred_test_gini))


Accuracy= 55.00000000000001
[[1 1 3 0]
 [0 5 0 1]
 [1 3 0 0]
 [0 0 0 5]]
              precision    recall  f1-score   support

           0       0.50      0.20      0.29         5
           1       0.56      0.83      0.67         6
           2       0.00      0.00      0.00         4
           3       0.83      1.00      0.91         5

    accuracy                           0.55        20
   macro avg       0.47      0.51      0.47        20
weighted avg       0.50      0.55      0.50        20



In [79]:
accuracy_3 = round(accuracy_score(y_test,y_pred_test_gini),4)
precision_3 = round(precision_score(y_test,y_pred_test_gini,average = 'macro'),4)
recall_3 = round(recall_score(y_test,y_pred_test_gini, average = 'macro'),4)
f1_3 = round(f1_score(y_test,y_pred_test_gini, average = 'macro'),4)
print('Accuracy Score   : ', accuracy_3)
print('Precision Score  : ', precision_3)
print('Recall Score     : ', recall_3)
print('f1-Score         : ', f1_3)
print('Confusion Matrix :\n',confusion_matrix(y_test,y_pred_test_gini))

Accuracy Score   :  0.55
Precision Score  :  0.4722
Recall Score     :  0.5083
f1-Score         :  0.4654
Confusion Matrix :
 [[1 1 3 0]
 [0 5 0 1]
 [1 3 0 0]
 [0 0 0 5]]


# RandomforestClassifier

In [32]:
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings('ignore')

In [33]:
modelRFC = RandomForestClassifier()

In [34]:
#Model on default/normal data splitted
modelRFC.fit(x_train,y_train)

RandomForestClassifier()

In [35]:
y_pred_train_RFC= modelRFC.predict(x_train)
acc = accuracy_score(y_train, y_pred_train_RFC) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_train, y_pred_train_RFC))
print(classification_report(y_train,y_pred_train_RFC))

Accuracy = 100.0
[[15  0  0  0  0]
 [ 0 16  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0  2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        10
           3       1.00      1.00      1.00        16
           4       1.00      1.00      1.00         2

    accuracy                           1.00        59
   macro avg       1.00      1.00      1.00        59
weighted avg       1.00      1.00      1.00        59



In [36]:
y_pred_test_RFC= modelRFC.predict(x_test)
acc = accuracy_score(y_test, y_pred_test_RFC) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_test, y_pred_test_RFC))
print(classification_report(y_test,y_pred_test_RFC))

Accuracy = 100.0
[[5 0 0 0]
 [0 6 0 0]
 [0 0 4 0]
 [0 0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [71]:
accuracy_4 = round(accuracy_score(y_test,y_pred_test_RFC),4)
precision_4 = round(precision_score(y_test,y_pred_test_RFC,average = 'macro'),4)
recall_4 = round(recall_score(y_test,y_pred_test_RFC, average = 'macro'),4)
f1_4 = round(f1_score(y_test,y_pred_test_RFC, average = 'macro'),4)
print('Accuracy Score   : ', accuracy_4)
print('Precision Score  : ', precision_4)
print('Recall Score     : ', recall_4)
print('f1-Score         : ', f1_4)
print('Confusion Matrix :\n',confusion_matrix(y_test,y_pred_test_RFC))

Accuracy Score   :  1.0
Precision Score  :  1.0
Recall Score     :  1.0
f1-Score         :  1.0
Confusion Matrix :
 [[5 0 0 0]
 [0 6 0 0]
 [0 0 4 0]
 [0 0 0 5]]


# ADABOOST

In [37]:
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier

In [38]:
modelab = AdaBoostClassifier()

In [39]:
#Model on default/normal data splitted
modelab.fit(x_train,y_train)

AdaBoostClassifier()

In [40]:
y_pred_train_ab= modelab.predict(x_train)
acc = accuracy_score(y_train, y_pred_train_ab) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_train, y_pred_train_ab))
print(classification_report(y_train,y_pred_train_ab))

Accuracy = 71.1864406779661
[[ 0 15  0  0  0]
 [ 0 16  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 16  0]
 [ 0  2  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        15
           1       0.48      1.00      0.65        16
           2       1.00      1.00      1.00        10
           3       1.00      1.00      1.00        16
           4       0.00      0.00      0.00         2

    accuracy                           0.71        59
   macro avg       0.50      0.60      0.53        59
weighted avg       0.57      0.71      0.62        59



In [41]:
y_pred_test_ab= modelab.predict(x_test)
acc = accuracy_score(y_test, y_pred_test_ab) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_test, y_pred_test_ab))
print(classification_report(y_test,y_pred_test_ab))

Accuracy = 65.0
[[0 5 0 0]
 [0 6 0 0]
 [0 1 3 0]
 [0 1 0 4]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.46      1.00      0.63         6
           2       1.00      0.75      0.86         4
           3       1.00      0.80      0.89         5

    accuracy                           0.65        20
   macro avg       0.62      0.64      0.59        20
weighted avg       0.59      0.65      0.58        20



In [72]:
accuracy_5 = round(accuracy_score(y_test,y_pred_test_ab),4)
precision_5 = round(precision_score(y_test,y_pred_test_ab,average = 'macro'),4)
recall_5 = round(recall_score(y_test,y_pred_test_ab, average = 'macro'),4)
f1_5 = round(f1_score(y_test,y_pred_test_ab, average = 'macro'),4)
print('Accuracy Score   : ', accuracy_5)
print('Precision Score  : ', precision_5)
print('Recall Score     : ', recall_5)
print('f1-Score         : ', f1_5)
print('Confusion Matrix :\n',confusion_matrix(y_test,y_pred_test_ab))

Accuracy Score   :  0.65
Precision Score  :  0.6154
Recall Score     :  0.6375
f1-Score         :  0.5944
Confusion Matrix :
 [[0 5 0 0]
 [0 6 0 0]
 [0 1 3 0]
 [0 1 0 4]]


# GradientBoostingClassifier

In [42]:
modelgb = GradientBoostingClassifier()

In [43]:
modelgb.fit(x_train,y_train)

GradientBoostingClassifier()

In [44]:
y_pred_train_gb= modelgb.predict(x_train)
acc = accuracy_score(y_train, y_pred_train_gb) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_train, y_pred_train_gb))
print(classification_report(y_train,y_pred_train_gb))

Accuracy = 100.0
[[15  0  0  0  0]
 [ 0 16  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0  2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        10
           3       1.00      1.00      1.00        16
           4       1.00      1.00      1.00         2

    accuracy                           1.00        59
   macro avg       1.00      1.00      1.00        59
weighted avg       1.00      1.00      1.00        59



In [45]:
y_pred_test_gb= modelgb.predict(x_test)
acc = accuracy_score(y_test, y_pred_test_gb) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_test, y_pred_test_gb))
print(classification_report(y_test,y_pred_test_gb))

Accuracy = 95.0
[[5 0 0 0]
 [0 6 0 0]
 [0 1 3 0]
 [0 0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       0.86      1.00      0.92         6
           2       1.00      0.75      0.86         4
           3       1.00      1.00      1.00         5

    accuracy                           0.95        20
   macro avg       0.96      0.94      0.95        20
weighted avg       0.96      0.95      0.95        20



In [73]:
accuracy_6 = round(accuracy_score(y_test,y_pred_test_gb),4)
precision_6 = round(precision_score(y_test,y_pred_test_gb,average = 'macro'),4)
recall_6 = round(recall_score(y_test,y_pred_test_gb, average = 'macro'),4)
f1_6 = round(f1_score(y_test,y_pred_test_gb, average = 'macro'),4)
print('Accuracy Score   : ', accuracy_6)
print('Precision Score  : ', precision_6)
print('Recall Score     : ', recall_6)
print('f1-Score         : ', f1_6)
print('Confusion Matrix :\n',confusion_matrix(y_test,y_pred_test_gb))

Accuracy Score   :  0.95
Precision Score  :  0.9643
Recall Score     :  0.9375
f1-Score         :  0.9451
Confusion Matrix :
 [[5 0 0 0]
 [0 6 0 0]
 [0 1 3 0]
 [0 0 0 5]]


# XGBClassifier

In [46]:
from xgboost import XGBClassifier

In [47]:
modelxgb=XGBClassifier()

In [48]:
modelxgb.fit(x_train,y_train);

In [49]:
y_pred_train_xgb= modelxgb.predict(x_train)
acc = accuracy_score(y_train, y_pred_train_xgb) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_train, y_pred_train_xgb))
print(classification_report(y_train,y_pred_train_xgb))

Accuracy = 100.0
[[15  0  0  0  0]
 [ 0 16  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0  2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        10
           3       1.00      1.00      1.00        16
           4       1.00      1.00      1.00         2

    accuracy                           1.00        59
   macro avg       1.00      1.00      1.00        59
weighted avg       1.00      1.00      1.00        59



In [50]:
y_pred_test_xgb= modelxgb.predict(x_test)
acc = accuracy_score(y_test, y_pred_test_xgb) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_test, y_pred_test_xgb))
print(classification_report(y_test,y_pred_test_xgb))

Accuracy = 95.0
[[5 0 0 0]
 [0 6 0 0]
 [0 1 3 0]
 [0 0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       0.86      1.00      0.92         6
           2       1.00      0.75      0.86         4
           3       1.00      1.00      1.00         5

    accuracy                           0.95        20
   macro avg       0.96      0.94      0.95        20
weighted avg       0.96      0.95      0.95        20



In [74]:
accuracy_7 = round(accuracy_score(y_test,y_pred_test_xgb),4)
precision_7 = round(precision_score(y_test,y_pred_test_xgb,average = 'macro'),4)
recall_7 = round(recall_score(y_test,y_pred_test_xgb, average = 'macro'),4)
f1_7 = round(f1_score(y_test,y_pred_test_xgb, average = 'macro'),4)
print('Accuracy Score   : ', accuracy_7)
print('Precision Score  : ', precision_7)
print('Recall Score     : ', recall_7)
print('f1-Score         : ', f1_7)
print('Confusion Matrix :\n',confusion_matrix(y_test,y_pred_test_xgb))

Accuracy Score   :  0.95
Precision Score  :  0.9643
Recall Score     :  0.9375
f1-Score         :  0.9451
Confusion Matrix :
 [[5 0 0 0]
 [0 6 0 0]
 [0 1 3 0]
 [0 0 0 5]]


# LGBMClassifier

In [51]:
import lightgbm

In [52]:
import pandas as pd
print(pd.__version__)

1.5.3


In [53]:
from lightgbm import LGBMClassifier

In [54]:
modellgbm=LGBMClassifier()

In [55]:
modellgbm.fit(x_train,y_train)

LGBMClassifier()

In [56]:
y_pred_train_lgbm= modellgbm.predict(x_train)
acc = accuracy_score(y_train, y_pred_train_lgbm) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_train, y_pred_train_lgbm))
print(classification_report(y_train,y_pred_train_lgbm))

Accuracy = 100.0
[[15  0  0  0  0]
 [ 0 16  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0  2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        10
           3       1.00      1.00      1.00        16
           4       1.00      1.00      1.00         2

    accuracy                           1.00        59
   macro avg       1.00      1.00      1.00        59
weighted avg       1.00      1.00      1.00        59



In [57]:
y_pred_test_lgbm= modellgbm.predict(x_test)
acc = accuracy_score(y_test, y_pred_test_lgbm) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_test, y_pred_test_lgbm))
print(classification_report(y_test,y_pred_test_lgbm))

Accuracy = 100.0
[[5 0 0 0]
 [0 6 0 0]
 [0 0 4 0]
 [0 0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [75]:
accuracy_8 = round(accuracy_score(y_test,y_pred_test_lgbm),4)
precision_8 = round(precision_score(y_test,y_pred_test_lgbm,average = 'macro'),4)
recall_8 = round(recall_score(y_test,y_pred_test_lgbm, average = 'macro'),4)
f1_8 = round(f1_score(y_test,y_pred_test_lgbm, average = 'macro'),4)
print('Accuracy Score   : ', accuracy_8)
print('Precision Score  : ', precision_8)
print('Recall Score     : ', recall_8)
print('f1-Score         : ', f1_8)
print('Confusion Matrix :\n',confusion_matrix(y_test,y_pred_test_lgbm))

Accuracy Score   :  1.0
Precision Score  :  1.0
Recall Score     :  1.0
f1-Score         :  1.0
Confusion Matrix :
 [[5 0 0 0]
 [0 6 0 0]
 [0 0 4 0]
 [0 0 0 5]]


# Naive Bayes(multinomialNB)

In [58]:
from sklearn.naive_bayes import MultinomialNB as MB
from sklearn.naive_bayes import GaussianNB as GB

In [59]:
modelmb=MB()

In [60]:
modelmb.fit(x_train,y_train)

MultinomialNB()

In [61]:
y_pred_train_mb= modelmb.predict(x_train)
acc = accuracy_score(y_train, y_pred_train_mb) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_train, y_pred_train_mb))
print(classification_report(y_train,y_pred_train_mb))

Accuracy = 96.61016949152543
[[15  0  0  0  0]
 [ 0 16  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 16  0]
 [ 0  2  0  0  0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.89      1.00      0.94        16
           2       1.00      1.00      1.00        10
           3       1.00      1.00      1.00        16
           4       0.00      0.00      0.00         2

    accuracy                           0.97        59
   macro avg       0.78      0.80      0.79        59
weighted avg       0.94      0.97      0.95        59



In [62]:
y_pred_test_mb= modelmb.predict(x_test)
acc = accuracy_score(y_test, y_pred_test_mb) * 100
print("Accuracy =", acc)
print(confusion_matrix(y_test, y_pred_test_mb))
print(classification_report(y_test,y_pred_test_mb))

Accuracy = 95.0
[[5 0 0 0]
 [0 6 0 0]
 [0 0 3 1]
 [0 0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         6
           2       1.00      0.75      0.86         4
           3       0.83      1.00      0.91         5

    accuracy                           0.95        20
   macro avg       0.96      0.94      0.94        20
weighted avg       0.96      0.95      0.95        20



In [76]:
accuracy_9 = round(accuracy_score(y_test,y_pred_test_mb),4)
precision_9 = round(precision_score(y_test,y_pred_test_mb,average = 'macro'),4)
recall_9 = round(recall_score(y_test,y_pred_test_mb, average = 'macro'),4)
f1_9 = round(f1_score(y_test,y_pred_test_mb, average = 'macro'),4)
print('Accuracy Score   : ', accuracy_9)
print('Precision Score  : ', precision_9)
print('Recall Score     : ', recall_9)
print('f1-Score         : ', f1_9)
print('Confusion Matrix :\n',confusion_matrix(y_test,y_pred_test_mb))

Accuracy Score   :  0.95
Precision Score  :  0.9583
Recall Score     :  0.9375
f1-Score         :  0.9416
Confusion Matrix :
 [[5 0 0 0]
 [0 6 0 0]
 [0 0 3 1]
 [0 0 0 5]]


In [86]:
table = {'Classifier' : ['SVM Classifier', 'KNN Classifier', 'DecisionTree Classifier', 'RandomForest Classifier', 'AdaBoost Classifier', 'Gradient Boosting Classifier', 'Xtreme Gradient Boosting Classifier', 'Light Gradient Boosting Classifier','MultinomialNB Classifier'], 'Accuracy Score' : [accuracy_1, accuracy_2, accuracy_3, accuracy_4, accuracy_5, accuracy_6, accuracy_7, accuracy_8, accuracy_9], 'Precision Score' : [precision_1, precision_2, precision_3, precision_4, precision_5, precision_6, precision_7, precision_8,precision_9], 'Recall Score' : [recall_1, recall_2, recall_3, recall_4, recall_5, recall_6, recall_7, recall_8, recall_9], 'f1-Score' : [f1_1, f1_2, f1_3, f1_4, f1_5, f1_6, f1_7, f1_8,f1_9]}
table = pd.DataFrame(table)
table

Classifier  Accuracy Score  Precision Score  \
0                       SVM Classifier            0.90           0.9375   
1                       KNN Classifier            1.00           1.0000   
2              DecisionTree Classifier            0.55           0.4722   
3              RandomForest Classifier            1.00           1.0000   
4                  AdaBoost Classifier            0.65           0.6154   
5         Gradient Boosting Classifier            0.95           0.9643   
6  Xtreme Gradient Boosting Classifier            0.95           0.9643   
7   Light Gradient Boosting Classifier            1.00           1.0000   
8             MultinomialNB Classifier            0.95           0.9583   

   Recall Score  f1-Score  
0        0.8875    0.9008  
1        1.0000    1.0000  
2        0.5083    0.4654  
3        1.0000    1.0000  
4        0.6375    0.5944  
5        0.9375    0.9451  
6        0.9375    0.9451  
7        1.0000    1.0000  
8        0.9375    0.9416